/* Generated by Cython 0.28.5 */

#ifndef __PYX_HAVE__flowstar__interval
#define __PYX_HAVE__flowstar__interval


#ifndef __PYX_HAVE_API__flowstar__interval

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C void __pyx_f_8flowstar_8interval_set_precision(int, int __pyx_skip_dispatch);
__PYX_EXTERN_C int __pyx_f_8flowstar_8interval_get_precision(int __pyx_skip_dispatch);
__PYX_EXTERN_C flowstar::Interval __pyx_f_8flowstar_8interval_make_interval(PyObject *);
__PYX_EXTERN_C bool __pyx_f_8flowstar_8interval_overlaps(flowstar::Interval &, flowstar::Interval &);
__PYX_EXTERN_C void __pyx_f_8flowstar_8interval_interval_union(flowstar::Interval &, flowstar::Interval &);
__PYX_EXTERN_C void __pyx_f_8flowstar_8interval_interval_vect_union(std::vector<flowstar::Interval>  &, std::vector<flowstar::Interval>  &);
__PYX_EXTERN_C PyObject *__pyx_f_8flowstar_8interval_interval_to_tuple(flowstar::Interval &);
__PYX_EXTERN_C PyObject *__pyx_f_8flowstar_8interval_intervals_to_list(std::vector<flowstar::Interval>  &);
__PYX_EXTERN_C double __pyx_f_8flowstar_8interval_int_dist(flowstar::Interval &, flowstar::Interval &);
__PYX_EXTERN_C bool __pyx_f_8flowstar_8interval_int_diff(flowstar::Interval &, flowstar::Interval &, bool &, flowstar::Interval const &, flowstar::Interval const &);
__PYX_EXTERN_C bool __pyx_f_8flowstar_8interval_extdiv(flowstar::Interval &, flowstar::Interval &, bool &, flowstar::Interval const &, flowstar::Interval const &, flowstar::Interval const &);

#endif /* !__PYX_HAVE_API__flowstar__interval */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initinterval(void);
#else
PyMODINIT_FUNC PyInit_interval(void);
#endif

#endif /* !__PYX_HAVE__flowstar__interval */
